### ISSUE TITLE
Create articles and knowledgebase [2]

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#1]
- [ ] Create new role for site content editors
- [x] Create articles
- [ ] Create wiki-like knowledgebase (pages hierarchy, navigation, create pages)

Use one of:
- http://extensions.ckan.org/extension/drupal/ (+also python, does it work?)
- http://extensions.ckan.org/extension/wordpresser/ (+easy to find collaborators, tested)
- WP step-by-step: https://groups.google.com/forum/#!topic/ckan-global-user-group/qjvb3MiOcaU
- http://extensions.ckan.org/extension/pages/ (+tight_integration)

**Comment by KrzysztofMadejski** [comment]
https://groups.google.com/forum/#!topic/ckan-global-user-group/qjvb3MiOcaU

**Comment by Cain-Ish** [comment]
Need for home page

**Comment by KrzysztofMadejski** [comment]
Drupal & wordpresser works so so, better would be to import RSS feed and show it:
- https://danepublicznetest.wordpress.com/feed/
- https://danepublicznetest.wordpress.com/2015/02/26/first-post/feed/?withoutcomments=1

Why better?
- coherent look out-of-the-box: using CKAN styles; no need to theme wordpress
- can be connected with various external systems

And there's an extension for that: http://extensions.ckan.org/extension/feedcontent/

**Comment by KrzysztofMadejski** [comment]
Final solution:

Create articles as separate type of packages:
- [ ] schema enforcing only name and description
- [ ] create form for creation and template for displaying
- [ ] embed 4 on main page [limit, shortcut of description]

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish: Już jest przygotowane pod #15. Zmerguj się z develop.

Kod na stronę główną:
```
   {% for a in h.dp_recent_articles() %}
          <div>
            <h2>{{ a.title }}</h2>
            <p>{{ a.author }}</p>
            <p>{{ h.render_datetime(h.date_str_to_datetime(a.metadata_created)) }}</p>
            <p>{{ h.dp_shorten_article(a.notes, 200) }}</p>
          </div>
        {% else %}
            No articles found!
        {% endfor %}
```
