### ISSUE TITLE
Pokaż wszystkie filtry

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#102]
Obecnie, gdy w danym kryterium wyszukiwania (np. Tagi) jest wiele filtrów lista jest ucinana i pojawia się guzik do rozwijania. Jest on moim zdaniem kompletnie nie intuicyjny. Może pod listą powinien być link "Lista jest ucięta. Pokaż wszystkie wartości". A może jakoś inaczej? 

@ArekSoldon , @dominiku, @jadebs  - jakie pomysły na to macie?

![fireshot capture - administracja_publiczna - _ - http___localhost_5000_group_administracja_publiczna](https://cloud.githubusercontent.com/assets/849975/6900850/b80d4286-d709-11e4-8f12-2c7e1a1a11d2.png)

**Comment by ArekSoldon** [comment]
Można napisać pokaz wszystkie na dole 

Wysłane z iPhone'a

Dnia 30 mar 2015 o godz. 18:25 Krzysiek Madejski <notifications@github.com> napisał(a):

**Comment by KrzysztofMadejski** [comment]
Wywalić ikonkę u góry, wystylować Show More tak żeby był wyrówany do lewej i widoczny dla wszystkich.  

Na tej samej zasadzie zrobić Show Less jeżeli lista jest rozwinięta.

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish już to ogarnę.
