### ISSUE TITLE
Gdy brak opisu lub krótki tytuł datasety na liście nachodzą na siebie

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#108]
![fireshot capture - datasets - ckan - http___localhost_5000_dataset](https://cloud.githubusercontent.com/assets/849975/6916846/bb427bf6-d79f-11e4-9893-d476898b2835.png)

**Comment by Cain-Ish** [comment]
Fixed already
