### ISSUE TITLE
2 małę bugi

### ISSUE THREAD

**Issue by ArekSoldon** [DanePubliczneGovPl/ckanext-danepubliczne#109]
1. w tagach jak jest długi to nie zawija wierszy przy aktywnym

![screen shot 2015-04-01 at 08 50 29](https://cloud.githubusercontent.com/assets/3994690/6935905/70814cc0-d84c-11e4-9c22-ea3eedc3d707.png)
![screen shot 2015-04-01 at 08 50 18 1](https://cloud.githubusercontent.com/assets/3994690/6935906/708bb05c-d84c-11e4-947e-96da590f6972.png)

2. w instytucjach troche szablon poleciał (data sety stykają się z linią od filtrów
![screen shot 2015-04-01 at 08 51 19](https://cloud.githubusercontent.com/assets/3994690/6935904/707d2884-d84c-11e4-8f58-4b91eeb6156e.png)

**Comment by Cain-Ish** [comment]
fixed already
