### ISSUE TITLE
Edycja zasobu i jednostki (uwagi do szablonu)

### ISSUE THREAD

**Issue by shutdownrunner** [DanePubliczneGovPl/ckanext-danepubliczne#125]
* usunąć niepotrzebny aside (pasuje do przeglądania zasobów i jednostek, ale w oknie edycji raczej niepotrzebne)
* dodać tytuł o treści np.: Edycja: [nazwa zasobu/jednostki] - może wyglądać różnie przy długich nazwach
* (i propozycja poprawki estetycznej) zwiększyć wysokość pól tekstowych nazwa i url (teraz wydają się za niskie)
![edycja zasobu](https://cloud.githubusercontent.com/assets/1592050/6937065/ce65ca08-d858-11e4-94b7-84074de881cc.png)

**Comment by KrzysztofMadejski** [comment]
przeniesione do #131
