### ISSUE TITLE
Ostylować stronę edycji zbiorów danych

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#131]
http://localhost:5000/pl/dataset/edit/baza_teleadresowa_administracji_zespolonej
- [x] taby u góry
- [x] akcje marginesy
- [x] przycisk usuwania / zachowania Dodatkowych metadanych [prostokątny z tekstem jak wszystkie inne]
- [x] usunąć niepotrzebny aside (pasuje do przeglądania zasobów i jednostek, ale w oknie edycji raczej niepotrzebne)
- [x] dodać tytuł o treści np.: Edycja: [nazwa zasobu/jednostki] - może wyglądać różnie przy długich nazwach
- [ ] (i propozycja poprawki estetycznej) zwiększyć wysokość pól tekstowych nazwa i url (teraz wydają się za niskie) 

![dataset_edit](https://cloud.githubusercontent.com/assets/849975/6953606/b9ba109c-d8ca-11e4-99a8-de19bcb1e972.png)

**Comment by Cain-Ish** [comment]
Trzeba wystawić/ustawić nazwe dataset w tytule (/package/edit.html)

**Comment by KrzysztofMadejski** [comment]
jeszcze jak przejdziesz na Zasoby to jest sidebar i się wywala
