### ISSUE TITLE
Main page [1]

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#15]
Uwagi odnośnie dostępności tutaj: https://symu.co/hyjgac

**Comment by KrzysztofMadejski** [comment]
@ArekSoldon wrzuć tu proszę PSD Strony Głównej dla Maria

**Comment by ArekSoldon** [comment]
https://dl.dropboxusercontent.com/u/19244622/dane.psd.zip

**Comment by KrzysztofMadejski** [comment]
TODO: Backend pod kategorie

**Comment by KrzysztofMadejski** [comment]
Gotowa do testowania na serwerze deweloperskim.

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish poprawki

![welcome_-_dane_publiczne](https://cloud.githubusercontent.com/assets/849975/6480065/89f169c8-c24f-11e4-8b74-81cb3e05fa1e.png)
![welcome_-_dane_publiczne 2](https://cloud.githubusercontent.com/assets/849975/6480069/95412200-c24f-11e4-8895-ac1aa27d9ac7.png)

> plus hoovery trzeba zrobić do kwadratów:
na kolory
2959a6   |   123246   |   4b5f74  |  482054
962701  |  213c89   |   b14600  |  095b92
066623
lub jakoś z automatu ściemnić wszystkie przy hooverze jak tak będzie łatwiej

idziemy w opcję automatycznego ściemniania

**Comment by shutdownrunner** [comment]
Czy nie lepiej byłoby tak upakować boksy, żeby przy mniejszej rozdzielczości 768-~1000px szerokości były 3 boksy w rzędzie? W załączeniu zrzut ekranu po zmianie szerokości .span3 na 33% zamiast 166px. Zrzut zrobiony przy szerokości okna ok. 900 px

![main-box-size](https://cloud.githubusercontent.com/assets/1592050/6506631/d9187426-c34c-11e4-80fa-585e019e647e.png)

**Comment by KrzysztofMadejski** [comment]
Widoki responsywne będziemy dopracowywać po stworzeniu pełnej szaty dla dużych szerokości: https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/issues/33

Dodam tam odnośnik, aby pamiętać o tej uwadze.
