### ISSUE TITLE
Filtr "Otwartość zasobu"

### ISSUE THREAD

**Issue by ghost** [DanePubliczneGovPl/ckanext-danepubliczne#157]
Pytanie, czy gwiazdki powinny być ułożone wedle stopnia otwartości czy liczby zasobów. Rozsądniejsza wydaje się opcja po stopniu otwartości.

Teraz jest tak:
![otwartosc](https://cloud.githubusercontent.com/assets/1592050/7045122/26f81ca0-ddfb-11e4-8e6c-197f8c331837.png)

**Comment by KrzysztofMadejski** [comment]
Tu fajnie jakby sort_field był argumentem helpera. Dzięki temu w template będzie można sterować sortowaniem.
