### ISSUE TITLE
Link “Przejdź do treści” 

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#171]
obecnie ukryty - pokazać go co najmniej “na fokusie” tak żeby i widzący korzystający tylko z klawiatury mogli z niego korzystać

przesunąć w kolejności kodu -  na sam początek, przed linki związane z logowaniem/kontem

**Comment by dominiku** [comment]
Kod do zabrania sobie na dostepnestrony.pl A dla inspiracji, przepięknie ma to rozwiązany nytimes.com. Fakt, że u nas ten przycisk powinien jednak być jako pierwszy w kolejności źródła.

**Comment by dominiku** [comment]
Hej, to jest niby nice to have, ale powinno wystarczyć 15-20 minut na wdrożenie. Wiesz, że ważone lekce nice to have to jest never happend.

**Comment by skuteli** [comment]
Rozumiem że chodzi o to, żeby ten link był niewidoczny, ale pojawiał się po zfokusowaniu? Zrobione

**Comment by KrzysztofMadejski** [comment]
Tak.

Tylko (1) to powinno się wyświetlać także dla niezalogowanych użytkowników. Trzeba to wyjąć z bloku 
```
{% block header_account_logged %}
    {% if c.userobj.sysadmin %}
 +    <li><a class="wcag_hide2 wcag_show_on_focus" href="#content">{{ _('Jump to content') }}</a></li>
```

(2) Kolejność focusa
Na NyTimes.com focus przeskakuje po:
- sections
- search
- skip to content (odsłaniane)
- skip to navigation (odsłaniane)
- później dopiero login/register i menusy
 
Można by w DanePubliczne zrobić tak, żeby kolejność focusa była:
- "Skip to content"
- wyszukiwarka, 
- menu
- zaloguj / zarejestruj,
- a później reszta strony?

@jadebs @dominiku: Czy jak focus będzie skakał po stronie góra-dół to może być mylące?

**Comment by skuteli** [comment]
Mi się wydaje że to jest trochę przesada żeby skakać focusem w dziwnej kolejności. Może lepiej dać dodatkowy link "przejdź do wyszukiwania"?

**Comment by KrzysztofMadejski** [comment]
Ok, Więc "Przejdź do treści", "Przejdź do wyszukiwania" umieszczone w lewym górnym

**Comment by KrzysztofMadejski** [comment]
Na Firefox 44.0 (Ubuntu 14) kliknięcie w "Przejdź do wyszukiwania" przenosi do pola, ale nie wyświetla focusu.
