### ISSUE TITLE
Niezrozumiała treść linków

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#172]
1. do wersji językowych EN, PL - alt nie działa do nie-grafiki wiec zmienić i dać rozwinięcie w ukryciu wizualnym + dodać info dla widzących w title
2. Niezrozumiały “Czytaj więcej” na głównej - uzupełnić o treść tytułu artykułu
3. niezrozumiały link API - wielu w miejscach, w sumie wyjaśniony tylko w jednym miejscu, a prowadzi do anglojęzycznych treści w http://docs.ckan.org/en/ckan-2.3/api/index.html  dodać ukrytą treść rozwijającą np. coś w stylu "Strona ze zbiorami numer" 
4. niezrozumiała treść linków paginacji np.  http://dp-dev.epf.p5.tiktalik.io/pl/dataset
5. niezrozumiała treść linków typu “zobacz”, “obejrzyj zasób” itp w pojedynczym datasecie np. http://dp-dev.epf.p5.tiktalik.io/pl/dataset/uslugi-laboratoryjne 
6. link bez treści  - do “Ustawień administratora” np. na http://dp-dev.epf.p5.tiktalik.io/ckan-admin nie ma treści - tylko w title, a to za mało dla niewidomych,

**Comment by skuteli** [comment]
Została paginacja

**Comment by KrzysztofMadejski** [comment]
1. do wersji językowych EN, PL: nice to have: aby EN i PL nie było czytane przez text-to-speech
2. pl ok, en: "read full" article of title "Title"
3. 
  - W widoku zbioru danych (http://localhost:5000/en/dataset/zbior1) oraz w widoku zasobu (http://localhost:5000/en/dataset/zbior1/resource/5b2f6a2c-cdbd-4778-92f3-e0ee85187f5e) "API" i "API do danych" + abbr
  - w stopce zamienić "API" na "dokumentacja API" (widoczne)
4. Problem: HTML generowany przez helper: ckanext/danepubliczne/templates/package/search.html:136
5. 
 - [ ] View_resource, edit_resource wywalić podkreślenia
 - [ ] Przed nazwą zasobu dodać ukryte"Zasób/resource:"
 - [ ] Do pobierz też dodać "zasób" (widoczne) 
6. "Ustawienia administratora" zrobić widoczne, wywalić młotek

**Comment by KrzysztofMadejski** [comment]
# Paging

- w ustawieniach dev.ini dodać `ckan.datasets_per_page = 1`

@krzysztofmadejski: nadpisać helper do paginacji:
- [ ] niech ymbol_rpev i symbol_next nie escapują html
- [ ] niech będzie callback do modyifkowania renderowania numeru strony

**Comment by KrzysztofMadejski** [comment]
@skuteli zrobiłem paging w naszym klonie ckan. 
`pip install -e git+https://github.com/DanePubliczneGovPl/ckan.git@release-v2.3.1#egg=ckan --update` powinno Ci wciągnąć zmiany (albo wejdź w katalog `src/ckan` i zrób `git pull`)

**Comment by skuteli** [comment]
Abbr api w linkach do sprawdzenia bo nie mogę znaleźć tego drugiego linku z api do danych.
