### ISSUE TITLE
Braki w tłumaczeniu

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#174]
- [x] 1. w filtrowaniu np. na http://dp-dev.epf.p5.tiktalik.io/pl/dataset anglojęzyczne <span class="visibility-hidden"> matching datasets</span> przy każdym kryterium
- [x] 2. komunikat błędu serwera
![nieprzetlumaczony komuniat bledu](https://cloud.githubusercontent.com/assets/11333543/7492511/ff58d126-f3f8-11e4-8dc7-f2c436f76970.png)

- [x] 3. tabelka podpowiedzi do formatowania Markdown - w dodawaniu datasetu
- [x] 4. informacje o błędach w formularzu edycji konta (Official posiition, Fullname etc.) np. http://dp-dev.epf.p5.tiktalik.io/user/edit/krzysztof-madejski-mac-9727, to samo w formularzu rejestracji np. http://dp-dev.epf.p5.tiktalik.io/user/register
- [x] 5. opcje w edycji zasobów - Data Store i jego zawartość np. http://dp-dev.epf.p5.tiktalik.io/dataset/e_administracja_w_oczach_internautow/resource_edit/237d9874-0b70-4e4f-aec1-bd4970528da1
- [x] 6. Anglojęzyczne title w drugim kroku dodawania datasetu na przyciskach “Link” oraz “Prześlij” - te przetłumaczone treści powinny być też w treści ukrytej tych linków. Dla niewidomych niemających często dostępu do title linki/przyciski te są niezrozumiałe.

**Comment by KrzysztofMadejski** [comment]
2, 3, 4, 5, 6 - aplikują się do oryginalnego CKAN także
