### ISSUE TITLE
Ograniczenia w obsłudze za pomocą klawiatury

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#175]
1. linki typu “Zobacz”, “pobierz” etc. w szczegółowym datasecie stają się niewidoczne na fokusie np. na http://dp-dev.epf.p5.tiktalik.io/pl/dataset/uslugi-laboratoryjne
2. “Zgłoś uwagi do zbioru” w pojedynczym datasecie - fokus klawiatury nie oznacza samego przycisku tylko wchodzi od razu do środka formularza. Użytkownik nawet nie domyśla się że tam coś “w środku jest”. Nie ma opcji rozwinięcia tego formularza za pomocą klawiatury.
3. za pomocą klawiatury nie można usunąć wprowadzonych słów kluczowych przy wprowadzaniu datasetu - Jest to też niedostępna dla czytników - nie ma treści link zamykania, nie wejdziesz klawiaturą bo wspomniany tabindex -1
4. niedostępne z poziomu klawiatury pola checkbox np. w “Warunki ponownego wykorzystania informacji...” http://dp-dev.epf.p5.tiktalik.io/dataset/edit/my-dataset#markdown , to samo w polu “Zapamiętaj” przy logowaniu

**Comment by dominiku** [comment]
5. Kolor fokusu jest zdecydowanie za jasny. Zmiana na jakiś ładny pomarańczowy posłużyłaby jego widoczności.

**Comment by KrzysztofMadejski** [comment]
Kasowanie słów kluczowych - trzeba wejść w pole i dać backspace. strzałkami można się przemieszczać między słowami.

Zostało:
- “Zgłoś uwagi do zbioru” w pojedynczym datasecie. Użytkownik nawet nie domyśla się że tam coś “w środku jest”. Nie ma opcji rozwinięcia tego formularza za pomocą klawiatury.
- niedostępne z poziomu klawiatury pola checkbox np. w “Warunki ponownego wykorzystania informacji...” http://dp-dev.epf.p5.tiktalik.io/dataset/edit/my-dataset#markdown , to samo w polu “Zapamiętaj” przy logowaniu
- Kolor fokusu jest zdecydowanie za jasny. Zmiana na jakiś ładny pomarańczowy posłużyłaby jego widoczności.

**Comment by skuteli** [comment]
zostało: 
niedostępne z poziomu klawiatury pola checkbox np. w “Warunki ponownego wykorzystania informacji...” http://dp-dev.epf.p5.tiktalik.io/dataset/edit/my-dataset#markdown , to samo w polu “Zapamiętaj” przy logowaniu

**Comment by KrzysztofMadejski** [comment]
checkboxy: zastapic helper `{% snippet` 'em

**Comment by skuteli** [comment]
Powinno śmigać
