### ISSUE TITLE
Zbyt mały kontrast 

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#176]
1. kontrast między tekstem a linkiem na http://dp-dev.epf.p5.tiktalik.io/pl/about - linki nie podkreślone, więc kontrast powinien być minimum 3:1 a jest 2,1:1
2. kontrast informacji o błędzie w polu formularza , ok. 3,9:1 np. na http://dp-dev.epf.p5.tiktalik.io/pl/user/register
3. placeholdery i podpowiedzi odnośnie hasła o zbyt małym kontraście do tła np. http://dp-dev.epf.p5.tiktalik.io/pl/user/register

**Comment by KrzysztofMadejski** [comment]
Do poprawy jeszcze następujące elementy:
- fokus klawiatury podczas przechodzenia pomiędzy elementami strony klawiszem TAB (czerwień i pogrubić?)
- poniższe screeny
![zrzut-3](https://cloud.githubusercontent.com/assets/849975/15143706/60011472-16ab-11e6-9461-3108eb80e7ae.jpg)
![zrzut-2](https://cloud.githubusercontent.com/assets/849975/15143709/61882cd6-16ab-11e6-9005-2da9ab5d0621.jpg)
![zrzut-1](https://cloud.githubusercontent.com/assets/849975/15143712/6328b7b8-16ab-11e6-9203-2557b25cb40d.jpg)

**Comment by KrzysztofMadejski** [comment]
@akustra

**Comment by KrzysztofMadejski** [comment]
Fokus sprawdzić w Firefoxie
