### ISSUE TITLE
Fałszywa lista

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#180]
główna lista na http://dp-dev.epf.p5.tiktalik.io/pl/about robiona z ręki a nie <ol>

**Comment by KrzysztofMadejski** [comment]
jak powinna być zrobiona @jadebs ?

**Comment by jadebs** [comment]
tak, prawda, gra nie wydaje się warta świeczki. Cofam com powiedział :) jest dobrze.
