### ISSUE TITLE
validacja kodu

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#181]
przykładowo, dla pokazania żebyście to jeszcze potestowali sami http://validator.w3.org/check?uri=http%3A%2F%2Fdp-dev.epf.p5.tiktalik.io%2F

**Comment by KrzysztofMadejski** [comment]
> A charset attribute on a meta element found after the first 512 bytes

to trzeb w fantastic poprawić w oryginalnym CKAN przesuwajac inject < link > dalej
