### ISSUE TITLE
Problemy ze zgobnością id z label for

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#185]
1. np. http://dp-dev.epf.p5.tiktalik.io/dataset/edit/my-dataset#markdown - niezgodne id z tym wskazanym w label for - w polu “Kategoria”
2. np. http://dp-dev.epf.p5.tiktalik.io/dataset/edit/my-dataset#markdown - zdublowane id w ramach jednej etykiety - w polach Dodatkowa metadana.

**Comment by KrzysztofMadejski** [comment]
Dla dodatkowej metadanej widzę:
field-extras-0-key
field-extras-1-key
itd. więc jak dla mnie to ok? @jadebs ?

**Comment by skuteli** [comment]
Nie widzę tu problemu. 
    <label class="control-label" for="field-category">Kategoria</label>
    <select id="field-category" name="category">
W dodatkowych metadanych id różnią się numerem.

**Comment by KrzysztofMadejski** [comment]
Dwa głosy na to, że to ok, więc zamykam.
