### ISSUE TITLE
Niezrozumiały komunikat błędy

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#187]
Na drugim kroku dodawania datasetu otrzymujemy komunikat błędu, który nie mówi jasno, w którym polu popełniony został błąd
![dataset blad](https://cloud.githubusercontent.com/assets/11333543/7492843/2cc1f4b4-f3fc-11e4-92f5-32b25fbfab68.png)

**Comment by akustra** [comment]
![screenshot from 2016-05-07 19 17 12](https://cloud.githubusercontent.com/assets/16704587/15093432/5d708ece-1488-11e6-9f90-7a331cc43780.png)
Na pierwszym kroku podobnie...

**Comment by KrzysztofMadejski** [comment]
A dodales wczesniej dostawce przez /organization/new ?

**Comment by KrzysztofMadejski** [comment]
Jedyne co wydaje się do poprawienia to "URL: Brakująca wartość" -> zamienić na "Wgraj plik lub podaj link do zasobu"
