### ISSUE TITLE
Etykiety przycisków w  podglądzie danych są tylko EN

### ISSUE THREAD

**Issue by ghost** [DanePubliczneGovPl/ckanext-danepubliczne#195]
Np. https://danepubliczne.gov.pl/pl/dataset/emerytury/resource/7ce0c4f8-1af3-4981-a792-cd1f5d90c0c6

Grid, map, filters, add series, search data itp. Warto przetłumaczyć te teksty, żeby serwis był w pełni zlokalizowany.

**Comment by KrzysztofMadejski** [comment]
Dzięki za uwagę!

Technicznie to zależne od https://github.com/ckan/ckan/issues/2403, do zaimplementowania w przyszłości

**Comment by KrzysztofMadejski** [comment]
Recline został przetłumaczony. @ghost, daj znać, czy taki efekt Cię satysfakcjonuje?

Widzę, że brakuje jeszcze tłumaczenia "Add Filter", ale jest to tak głęboko zaszyte w CKAN, że nie mogłem się do tego dobrać. Jeżeli to przeszkadza to skasuję, bo ta funkcjonalność jest dostępna przez przycisk `Filtry` -> `Dodaj filtr`.
