### ISSUE TITLE
Baza wiedzy widoczność artykułów

### ISSUE THREAD

**Issue by shutdownrunner** [DanePubliczneGovPl/ckanext-danepubliczne#196]
Przed publikacją artykułu warto by mieć możliwość jego podglądu. Najprostsze rozwiązanie to możliwość ustawiania wpisom widoczności: publiczny, projekt. Taka możliwość jest przy zbiorach danych.

**Comment by KrzysztofMadejski** [comment]
Artykuły o widoczności 'projekt' będą dostępne z poziomu menu Moje konto -> Moje zbiory danych
