### ISSUE TITLE
Dodać captchę do formularzy na stronie

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#211]
**Uzasadnienie**
Otrzymujemy bardzo dużo spamu wysyłanego automatycznie przez formularze, powinniśmy to ograniczyć.

**Efekt**
Captcha powinna być wyświetlana w formularzu:
* *Zaproponuj nowy zbiór danych* w stopce
![dp-form-stopka](https://cloud.githubusercontent.com/assets/849975/13615598/83c60aae-e576-11e5-95c4-429dfb3a3d48.PNG)
* *Zgłoś uwagi do zbioru* w lewym sidebarze na dowolnym zbiorze (np. [tu](https://danepubliczne.gov.pl/dataset/realizacja_budzetu_na_refundacje_lekow)) 
![dp-form-zbior](https://cloud.githubusercontent.com/assets/849975/13615672/dfffec86-e576-11e5-88e8-0e5f822d3b0f.PNG)

** Technicznie **
1) Wdrożenie [reCAPTCHA](https://www.google.com/recaptcha/intro/index.html)
2) [Zostało to zrobione](https://github.com/ckan/ckan/pull/2407) w nowej wersji CKAN, więc backend można skopiować od nich (może nawet zrobić cherrypick do https://github.com/DanePubliczneGovPl/ckan)
3) Niech settingsy się identycznie nazywają, jak w rozwiązaniu już wdrożonym `ckan.recaptcha.privatekey`, `ckan.recaptcha.publickey`, `ckan.recaptcha.version`

**Comment by dominiku** [comment]
Hej, tak jak rzadko śledzę issuesy Waszego serwisu, tak traf chciał, że zobaczyłem to zgłoszenie.

reCaptcha nie jest dostępna. Tzn. jeśli przepuści Cię po samym checkboksie, to nie ma większych problemów. Jednak w przypadku, kiedy włącza się okno z wyborem obrazków / audio captchą, to jest padaka.

Rozwiązaniem będzie dla Was wg mnie własna honeypot captcha.

W razie pytań dajcie znać.
