### ISSUE TITLE
Uncaught TypeError: $(...).fileupload is not a function

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#220]
Błąd występuje na głównej stronie.

Przyczyna: odwołanie do jupload występuje w globalnym dla strony skrypcie danepubliczne.js, ale jquery-fileupload.js jest tylko dodawany na niektórych stronach.

Rozwiązanie proponowane: Przerobić wywołanie  fileupload w danepubliczne.js,, tak aby na pustej liście zwróconej przez `$(".fileupload")` nie był wywoływany

**Comment by skuteli** [comment]
Do zamknięcia; sprawdzamy długość listy jquery.
