### ISSUE TITLE
Datasets list [2]

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#23]
https://symu.co/ywrgvs.s

@ArekSoldon popraw uwagi związane z dostępnością i podeślij tutaj PSD-ka

Korzystając z https://www.zenhub.io/ można wklejać tutaj wszelkie pliki.

**Comment by KrzysztofMadejski** [comment]
Przy okazji jak możesz usunąć komentarze, które poprawisz i nie będą istotne dla Maria to mu pomoże.

**Comment by ArekSoldon** [comment]
https://dl.dropboxusercontent.com/u/19244622/lista.psd.zip

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish można dłubać, później poprawimy kolory. W pierwszym komentarzu jest symu z uwagami odnośnie dostępności.

**Comment by ArekSoldon** [comment]
Poprawione kolory i kilka innych szczegółów. 

![lista](https://cloud.githubusercontent.com/assets/3994690/6458367/07da52c8-c183-11e4-9083-5f17dbeceabe.jpg)

**Comment by KrzysztofMadejski** [comment]
@ArekSoldon dzięki, podeślesz poprawione PSD coby jpg nie kłamał w żywe oczy apropo kontrastu :)

**Comment by ArekSoldon** [comment]
https://dl.dropboxusercontent.com/u/19244622/lista.psd%20copy.zip

**Comment by KrzysztofMadejski** [comment]
Zrobić zrzut bazy z danymi, opisać gdzie trzeba wystylować wygląd dla kategorii

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish wysłałem Ci mailem zrzut bazy danych do zaimportowania przez `paster db load dp-20150311 --config=/etc/ckan/default/dev.ini`
Dodatkowo `datastore` trzeba zaimportować przez pg-admina pewnie.

Do wystylowania pozostaje widok kategorii, np. [http://localhost:5000/group/administracja_publiczna](http://localhost:5000/group/administracja_publiczna)

Najpewniej poprzez template `templates/group/read.html`

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish nie za wątłe te rozdzielniki?

![screenshot from 2015-03-12 17 46 52](https://cloud.githubusercontent.com/assets/849975/6622871/b3e7aa94-c8df-11e4-87df-ff21b039f736.png)
