### ISSUE TITLE
Pojedynczy dataset [3]

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#24]
Uwagi:
- "follow" - dostępne dla zalogowanych użytkowników, u nas funkcjonuje jako "Dodaj do ulubionych"
- "social" - Na zasadzie "Udostępnij na ....". Zostawmy to gdzieś, jeżeli znajdziesz miejsce i Ci to zagra (jak nie to pomijamy, zawsze ręcznie można wyszerować). 

Content:
![dataset_single](https://cloud.githubusercontent.com/assets/849975/6414829/cc9f75d4-be9a-11e4-9720-17a5d57b552d.PNG)

**Comment by KrzysztofMadejski** [comment]
Zasób:

Jeżeli wgrywamy csv-kę to jest podgląd danych oraz przycisk `Data API`
![ckan-resource-data](https://cloud.githubusercontent.com/assets/849975/6414880/34296692-be9b-11e4-97ea-4b124fb1255e.PNG)

Każdy zasób ma 'gwiazdki otwartości':
![ckan-resource-rating](https://cloud.githubusercontent.com/assets/849975/6414889/419e8352-be9b-11e4-9384-5761d7c17adf.PNG)

Zalogowanym użytkownikom posiadającym uprawnienia do edycji powinien się pojawiać przycisk pozwalający na edycję (zarówno datasetu, jak i zasobu). Patrz `Manage`
![ckan-resource-edit](https://cloud.githubusercontent.com/assets/849975/6414926/8dfdaf2a-be9b-11e4-90bb-2f5dcb90b2b5.PNG)
:

**Comment by ArekSoldon** [comment]
![item](https://cloud.githubusercontent.com/assets/3994690/6459943/77d2f372-c193-11e4-9245-131649e3d9fd.jpg)

**Comment by ArekSoldon** [comment]
![item](https://cloud.githubusercontent.com/assets/3994690/6461005/4edc6274-c19c-11e4-8afb-e36d5bf0933f.jpg)

**Comment by KrzysztofMadejski** [comment]
@dominiku to jest gotowe do audytu

**Comment by dominiku** [comment]
Uwagi przygotowane przez @jadebs Są to głównie sugestie wdrożeniowe do front-endu, drobne uwagi użyteczności.

![pojedynczy_dataset_e_panstwo_jd](https://cloud.githubusercontent.com/assets/539978/6506771/b4d57bb2-c34d-11e4-83d5-75007947d868.jpg)

**Comment by KrzysztofMadejski** [comment]
Dzięki!

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish wywalamy social z lewej strony. Powinien dojść przycisk "Zgłoś uwagi (do zbioru danych)"

**Comment by KrzysztofMadejski** [comment]
@ArekSoldon podrzuc PSD ktory masz na szybko pls, @Cain-Ish  siada do tego

**Comment by ArekSoldon** [comment]
wszystkie screeny https://dl.dropboxusercontent.com/u/19244622/crip_all.zip

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish spójrz co zmieniłem w https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/commit/d452b1947f7162a5f54439d573c35c6a432121d4

Do poprawienia:
- Odstępy obok follow
- 'History' button oraz 'Manage' button do ostylowania na niebiesko (niech `class="btn"` tak ma domyślnie. 
- kreska pod 'Manage' button (po zalogowaniu) do usunięcia w tym widoku; może być on nad organizacją i tytułem
- wystyluj organizację, którą dodałem nad tytułem (szczególnie gdy user niezalogowany)
- Atrybuty w osobnych liniach:
```
Source https://administracja.mac.gov.pl/download/58/15410/BAZATELEADRESOWAnastrone.xls Last Updated March 13, 2015, 14:23 Created March 13, 2015, 14:22
```

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish zmerguj się z develop bo tam są te zmiany

**Comment by KrzysztofMadejski** [comment]
Gites!
