### ISSUE TITLE
Zmiany w kategoriach danych

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#247]
Wprowadzenie zmian w zakresie głównych kategorii danych dostępnych w CRIP:
- [x] zmniejszenie wysokości kafli określających główne kategorie danych dostępnych w CRIP o ok. 1/2 dotychczasowej wysokości z zachowaniem rozmiaru czcionek i wielkości ikony kategorii; 
- [ ] dodanie nowej kategorii Dane samorządowe, kolor tła kafla zgodny z istniejącą paletą przy zachowaniu kontrastu 4,5:1 (min. 3:1 przy czcionce nie mniejszej niż 18 pkt.

**Comment by KrzysztofMadejski** [comment]
Jestem sceptyczny co do dodania nowej kategorii Dane Samorządowe - przecież dodawane dane będą się łapać do istniejących kategorii danych (Społeczeństwo, Finanse, itp.). Moim zdaniem powinny to zostać stworzone jako dedykowany filtr.

**Comment by KrzysztofMadejski** [comment]
Pomysł: zrobić kafelek "dane samorządowe", ale nie robić z tego prawdziwej kategorii, tylko linkować do zaznaczonego filtra.

**Comment by danielmacyszyn** [comment]
Zmniejszenie kafli dokonało się w
https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/commit/2636987d0cf72b4cf79bbb55af5b824a63fac901

Sprawa dodania kategorii do wyjaśnienia z MC.

**Comment by KrzysztofMadejski** [comment]
Rozumiem, że finalnie ustalono, że kategoria "Dane samorządowe" nie doszła na rzecz filtra.

**Comment by danielmacyszyn** [comment]
Tak. Nie trzeba tworzyć tej kategorii.
