### ISSUE TITLE
Połączenie wyszukiwarek

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#248]
Połączenie wyszukiwarek w jedną; na podstronach działające tak, że pokazują w pierwszej kolejności wyniki dotyczące danej podstrony.

**Comment by danielmacyszyn** [comment]
Cel osiągnięty przez usunięcie wyszukiwarki z głównego menu. Jeśli będziemy mieli ją kiedyś przywracać, to powinna przeszukiwać "wszystko", tj: zbiory danych, artykuły, aplikacje i dostawców.
