### ISSUE TITLE
Wyświetlanie liczby odwiedzin i pobrań

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#249]
Na liście zbiorów danych. 

Sugeruje się wykorzystanie pól o kontrastowym tle wobec strony i wobec własnej etykiety (min. 4,5:1). Pola umieszczone poniżej tytułu zbioru (bezpośrednio pod): 
(1) jedno pole po lewej stronie, bez dodatkowej etykiety, zawiera listę formatów zasobów, 
(2) dwa pola po prawej stronie, z etykietami w postaci ikon oraz liczbami obok obrazującymi odpowiednio odwiedziny i pobrania. 

Dodanie informacji o API do danych, jeżeli występuje przy zasobie.

**Comment by KrzysztofMadejski** [comment]
Na liście zbiorów danych jak się liczą pobrania (pobierać można zasoby, a nie zbiory)? Jako suma pobrań wszystkich zasobów podlegających pod zbiór? 

Czy liczba odwiedzin  powinna się wyświetlać także na pojedynczym zbiorze (dot. zbioru), a także na liście zasobów zbioru (pobrania i odwiedziny)? Czy te liczby powinny się wyświetlać w widoku zasobu pojedynczego?

**Comment by danielmacyszyn** [comment]
Na liście zbiorów, liczba pobrań oznacza sumę pobrań wszystkich zasobów danego zbioru.

Liczba odwiedzin i pobrań wyświetla się też w widoku pojedynczego zbioru. Nie wyświetla się w widoku pojedynczego zasobu.

Informacje o API dodam przy okazji #261 - będzie na liście zbiorów i zasobów dla danego zbioru.

**Comment by KrzysztofMadejski** [comment]
@danielmacyszyn ciekawie jakby też liczba odwiedzin i pobrań pokazywała się per zasób na liście zasobów danego zbioru.

**Comment by KrzysztofMadejski** [comment]
Tu brakuje opisu zgodnego z wcag. Tekst z title powinien być przeniesiony do środka spana z klasą wcag_hide, tak aby te liczby były zrozumiałe dla niewidzących: https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/blob/f65b096d2ff643b7afcd580563a772ba26993dc3/ckanext/danepubliczne/templates/home/snippets/package_item.html#L33-L34
