### ISSUE TITLE
Login page [1]

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#25]
Content: http://demo.ckan.org/user/login

Create account, forget password proponuję bez zbędnego komentarza

**Comment by ArekSoldon** [comment]
![logowanie](https://cloud.githubusercontent.com/assets/3994690/6459427/bc5aa53a-c18e-11e4-88ab-7632766c4af7.jpg)

**Comment by ArekSoldon** [comment]
![main_0200](https://cloud.githubusercontent.com/assets/3994690/6460285/2ca80948-c196-11e4-875f-a124a5e3f2d4.jpg)

**Comment by KrzysztofMadejski** [comment]
@ArekSoldon: Dzięki, podeślij PSD jeszcze

**Comment by ArekSoldon** [comment]
https://dl.dropboxusercontent.com/u/19244622/login.psd.zip

**Comment by dominiku** [comment]
Uwagi przygotowane przez @jadebs Są to głównie sugestie wdrożeniowe do front-endu, drobne uwagi użyteczności.
![login_e_panstwo_jd](https://cloud.githubusercontent.com/assets/539978/6506766/a5ccaeba-c34d-11e4-837f-4103d9297b23.jpg)
