### ISSUE TITLE
Widok dostawców

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#251]
Zmniejszenie w kategorii Dostawcy wysokości belek, ograniczenie maksymalnej wysokości logo

**Comment by danielmacyszyn** [comment]
Załatwione w https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/commit/63f353298a142c03824e6d4dd306dc3caba341f4
