### ISSUE TITLE
Wybór filtrów

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#257]
Wprowadzeni zmian w funkcjonalności filtry. Po wybraniu jednego filtra pozostawienie podglądu pozostałych, niewybranych filtrów (wybór danej wartości filtra powoduje w lewym panelu tylko zaznaczenie/wyróżnienie tej wartości, wszystkie inne opcje są nadal widoczne).

**Comment by danielmacyszyn** [comment]
Filtry, które przekazujesz do SOLRa można tagować, aby następnie selektywnie wykluczać je z facetingu dla danego pola.

To jest dotychczasowe używanie parametru `fq` przez CKAN:
`fq=key1:val1 key2:val2`

Do każdego warunku trzeba dostawić tag:
`fq={!tag=key1}key1:val1 {!tag=key2}key2:val2`

Ale to nie zadziała, ponieważ instrukcja tagowania może być dostawiana tylko raz w parametrze `fq`. Dlatego trzeba skorzystać z tego, że:

> The fq param can be specified multiple times. Documents will only be included in the result if they are in the intersection of the document sets resulting from each fq.
http://wiki.apache.org/solr/CommonQueryParameters#fq

Trzeba zrobić coś takiego:
`fq={!tag=key1}key1:val1&fq={!tag=key2}key2:val2`

CKAN umożliwia takie konstruowanie zapytania do SOLRa, za pomocą **nieudokumentowanego parametru `fq_list`**

Gdy mamy już potagowane wszystkie filtry, to dla każdego pola facetingu, wykluczamy z niego filtr działający na tym samym polu co faceting.
