### ISSUE TITLE
Metadana dostawcy: typ

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#259]
Utworzenie nowej metadanej, wpisywanej do systemu CRIP na poziomie tworzenia nowego dostawcy, „rodzaj podmiotu,” która umożliwiałaby podział na instytucje administracji rządowej i samorządowej.

**Comment by KrzysztofMadejski** [comment]
Należy zmodyfikować schemę dostawcy: https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/blob/develop/ckanext/danepubliczne/schema/organization.py

A później także formularz, aby uwzględniał to pole: https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/blob/develop/ckanext/danepubliczne/templates/organization/snippets/organization_form.html

**Comment by danielmacyszyn** [comment]
@KrzysztofMadejski Dla wszystkich istniejących już dostawców trzeba ustawić pole institution_type=state. Jak to najlepiej zrobić?

**Comment by KrzysztofMadejski** [comment]
Jest ich tyle, że bym to ręcznie zrobił. Albo można zhackować INSERT-em do `group_extra` tylko revision_id trzeba dobrać właścwie. Porządnie to by było zrobić skrypt, który przez API pobiera dostawców, uzupełnia i zapisuje. 

Warto, też założyć, że brak wartości oznacza domyślnie jedną z nich (`state`) i tak wyświetlać w interfejsach.

**Comment by danielmacyszyn** [comment]
Załatwione w https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/commit/3f1ceb00fc9f6d27476d8332c7861b86e09418bb

Przy wdrażaniu na produkcję, trzeba dodać wpisy do `group_extra`, tak żeby istniejące organizacje miały `institution_type='state'`

**Comment by KrzysztofMadejski** [comment]
Type zmieniłeś na institution_type finalnie?

**Comment by danielmacyszyn** [comment]
Tak
