### ISSUE TITLE
Form to add datasets [3]

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#26]
Content: ![ckan](https://cloud.githubusercontent.com/assets/849975/6371180/3cf1d258-bcf9-11e4-8da8-2cd10f57a53d.png)

Zamiast license powinien być panel zawierający checkboxy z #13 
Krótki opis ideowy czym są datasety / objaśniający jak je tworzyć powinien gdzieś zostać.

**Comment by KrzysztofMadejski** [comment]
Przeszliśmy na CKAN 2.3. Teraz jest dwuetapowy wizard, ale to wiele dla Ciebie nie zmienia. :)

**Comment by ArekSoldon** [comment]
![add](https://cloud.githubusercontent.com/assets/3994690/6687905/902f2cde-ccaf-11e4-9ad8-8d6b21955eea.jpg)

**Comment by KrzysztofMadejski** [comment]
@jadebs jakieś uwagi do checkboxów? Poza tym chyba dużo nowego tu nie ma..

**Comment by jadebs** [comment]
1. Nie ma nagłówka h1, 
2. Zakładam, że są tu dwie zakładki - to dać je w <ul>
3. etykiety połączyć z polami przez <label><for>

Chyba tyle

**Comment by KrzysztofMadejski** [comment]
@jadebs coś Ci ucięło, albo zdjec nie wkleilo..

**Comment by jadebs** [comment]
Już podsyłam.
Rozumiem, że na ekran informacji o błędnie wypełnionych polach jeszcze przyjdzie czas. 
![fireshot pro screen capture 907 - -](https://cloud.githubusercontent.com/assets/11333543/6688781/5c57ac7c-ccb6-11e4-9d22-e5ec5a69a1b2.png)

**Comment by KrzysztofMadejski** [comment]
Błędnie wypełnione pola już w praktyce zrobimy.

**Comment by KrzysztofMadejski** [comment]
![fireshot capture - create dataset - dane publiczne_ - http___localhost_5000_dataset_new](https://cloud.githubusercontent.com/assets/849975/6798749/8648d0ec-d210-11e4-8e0f-9eb0602b5ad6.png)
