### ISSUE TITLE
Dostawca: Korekta tekstu etykiet

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#260]
Korekta tekstu etykiet w oknie dodawania nowego dostawcy: w nagłówku (tytule okna) tekst „Stwórz Kategorię” zmienić na „Utwórz Dostawcę lub modyfikuj istniejące zapisy” oraz tekst etykiety przycisku „Stwórz Dostawcę” zmienić na „Utwórz Dostawcę”

**Comment by KrzysztofMadejski** [comment]
To pewnie trzeba dodać `organization/new.html` i ustawić to jako dedykowany szablon w https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/blob/develop/ckanext/danepubliczne/schema/organization.py#L85

**Comment by danielmacyszyn** [comment]
Poprawiłem także podświetlanie właściwych pozycji w głównym menu, ale nie wszędzie. Widoki edycji artykułu lub aplikacji podświetlają nadal w menu głównym pozycję "Zbiory danych".

**Comment by KrzysztofMadejski** [comment]
Podczas dodawania:
- nagłówek okna nadal mówi "Stwórz kategorię"
- breadcrumb też niepoprawnie mówi "Home -> Kategorie -> Stwórz kategorię"
