### ISSUE TITLE
Pobieranie zasobów

### ISSUE THREAD

**Issue by danielmacyszyn** [DanePubliczneGovPl/ckanext-danepubliczne#265]
### Case 1:
**Tworzę nowy zbiór danych.** W drugim kroku, dodaję do niego zasób - wgrywam lokalny plik `data.csv`. Przechodzę na widok zbioru danych. Klikam "Pobierz zasób". Przeglądarka jest kierowana pod adres `data.csv` co oczywiście zwraca błąd.

### Case 2:
**Edytuję wcześniej utworzony zbiór danych.** Dodaje zasób - wgrywam lokalny plik `data.csv`. Przechodzę na widok zbioru danych. Klikam "Pobierz zasób". Przeglądarka przechodzi pod adres typu `http://192.168.96.160:5000/dataset/df7788b5-2b7e-43be-b5ce-ce650df5e94f/resource/76a07eaa-2a6f-47cb-8de5-82e9818d7989/download/data.csv` i poprawnie ściąga plik.

@KrzysztofMadejski Czy możesz potwierdzić takie zachowanie? Czy to jakiś błąd konfiguracji u mnie...

**Comment by KrzysztofMadejski** [comment]
Na szkoleniach to działa: http://szkolenia.danepubliczne.gov.pl/dataset/test-linki-do-zasobow

Zostaw to mi, przy przeglądaniu twoich zmian przyjrzę się temu uważnie.
