### ISSUE TITLE
Gdy dodaję aplikację linkując do obrazku to obraz wyświetla się niepoprawnie

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#266]
Ponieważ pełen url jest doklejany do ckanowej relatywnej ścieżki, np. http://127.0.0.1:5000/uploads/package/http://static.adzerk.net/Advertisers/b08a4d7b01a04852b914e7904a73b1b8.png

**Comment by danielmacyszyn** [comment]
Ukruto przycisk pozwalający na linkowanie do obrazków (można tylko uploadować).
