### ISSUE TITLE
Jak dodaję zbiór dostawcy to dostaję błąd po dodaniu zasobu

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#267]
Dodając jeden zasób i klikając "Zakończ" dostaję błąd:

```
File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/logic/action/create.py', line 307 in resource_create
  errors = e.error_dict['resources'][-1]
KeyError: 'resources'
```

Czasami, nie zawsze tak się dzieje.

**Comment by danielmacyszyn** [comment]
@KrzysztofMadejski Możesz dać więcej szczegółów pozwalających na reprodukcję błędu?

**Comment by KrzysztofMadejski** [comment]
Chyba to u siebie będę musiał zdiagnozować.

**Comment by KrzysztofMadejski** [comment]
Nie umiem tego powtórzyć, zakładam że to jakiś nieodświeżony kod lub dane. zamykam.
