### ISSUE TITLE
Single article [1]

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#27]
Content:
- Title
- Date of publication / author (given name + surname, no photo)
- Content

Artykułu mają opcję "dodaj do ulubionych" oraz "Udostępnij na ..." jeżeli na #24 też social zrobiłeś.

**Comment by ArekSoldon** [comment]
![artykul](https://cloud.githubusercontent.com/assets/3994690/6459970/a695c356-c193-11e4-82a8-4a2709507b44.jpg)

**Comment by KrzysztofMadejski** [comment]
To jeszcze brakuje dostawcy danych, metadanych i powiązanych zasobów.

![v1_jednostka](https://cloud.githubusercontent.com/assets/849975/6460750/4df26392-c19a-11e4-8247-61c0b305ac12.jpg)

**Comment by KrzysztofMadejski** [comment]
Super wygląda! To jeszcze PSDek. :)

**Comment by ArekSoldon** [comment]
https://dl.dropboxusercontent.com/u/19244622/artykul.psd.zip

**Comment by dominiku** [comment]
Uwagi przygotowane przez @jadebs Są to głównie sugestie wdrożeniowe do front-endu, drobne uwagi użyteczności.
![single_article_e_panstwo_jd](https://cloud.githubusercontent.com/assets/539978/6506745/7f33dd64-c34d-11e4-9bf3-ed662c78397a.jpg)

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish wyrzucamy stąd przyciski do udostępniania w social z lewej strony. U dołu powinna być krótka informacja o licencji.

**Comment by KrzysztofMadejski** [comment]
Przegadajmy to jutro. Moja propozycja:
- follow obok manage
- licencja na dół
- number of followers wylatuje

Tylko, żeby tak było wyłącznie dla artykułów.

![fireshot capture - tytul - articles - dane publiczne - http___localhost_5000_dataset_tytul](https://cloud.githubusercontent.com/assets/849975/6623196/c2360288-c8e1-11e4-9c16-1b5ba1704ebf.png)

**Comment by KrzysztofMadejski** [comment]
@dominiku w czym robicie takie ładne adnotacje na tych obrazkach? Jak widisz mi to średnio wychodzi :P

**Comment by dominiku** [comment]
Fireshot, rozszerzenie do Firefoxa. Jest darmowe, my mamy wersję pro, ale w
większości przypadków nie jest potrzebne.

W dniu 12 marca 2015 18:02 użytkownik Krzysiek Madejski <
notifications@github.com> napisał:

> @dominiku <https://github.com/dominiku> w czym robicie takie ładne
> adnotacje na tych obrazkach? Jak widisz mi to średnio wychodzi :P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/issues/27#issuecomment-78528508>
> .
>



-- 
Dziękuję i pozdrawiam, Dominik Paszkiewicz

*Audyty, doradztwo i szkolenia w zakresie dostępności **i technologii
internetowych.*
tel: +48 608 059 999 / skype: dominik.paszkiewicz / www.dostepne.info
