### ISSUE TITLE
Rozpoznawanie otwartości feedów ATOM

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#275]
Przypadek: https://danepubliczne.gov.pl/dataset/dane-z-krajowego-rejestru-urzedowego-podzialu-terytorialnego-kraju/resource/fcd90347-1166-4efe-ac83-8730997e0005

Powinna zostać przyznana co najmniej jedna gwiazdka (obecnie jest zero). W praktyce powinny zostać przyznane trzy lub cztery dla feedu ATOM. 

PS. Tam są dodatkowo wykorzystane NS: `xmlns:georss="http://www.georss.org/georss/11" xmlns:inspire_dls="http://inspire.ec.europa.eu/schemas/inspire_dls/1.0" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/"`

**Comment by k255** [comment]
Jakiej wersji dodatku CKAN-QA używa portal danepublicznegovpl?
Myślę, że problem tkwi w stosowaniu starszej wersji tego dodatku, który próbuje dokonać oceny typu danych najpierw na podstawie analizy żądania http z wykorzystaniem biblioteki mimetypes python'a, następnie analizy zawartości content-type w nagłówku odpowiedzi i w dalszej kolejności analizując pole format (wypełniane w czasie wprowadzania danych). Dla api z tego issue, biblioteka mimetypes wykorzystywana w starej wersji ckan-qa nie radzi sobie z detekcją typu. Jeśli nawet by się to powiodło, to api zwraca typ application/xhtml+xml, który nie jest rozpoznawany przez stary ckan-qa.

Rozwiązaniem wydaje się być zmiana konfiguracji serwera udostępniającego dane na application/xml lub ustalenie pola format na XML, przy wprowadzaniu danych.

Najlepszym jednak rozwiązaniem byłaby aktualizacja ckan-qa do nowsze wersji, co wyeliminowałoby problem, gdyż tam typ danych ocenia się na podstawie zawartości pliku - biblioteką python-magic, a jeśli to xml, to dodatkowo analizą tagu głównego (w tym przypadku Atom zostałby rozpoznany na podstawie tagu <feed>).

Jeśli typ zostanie poprawnie rozpoznany zostaną przyznane trzy gwiazdki niezależnie od wersji:
wersja ckan-qa danepublicznegovpl - https://github.com/DanePubliczneGovPl/ckanext-qa/blob/master/ckanext/qa/tasks.py#L46
wersja master ckan-qa - https://github.com/ckan/ckanext-qa/blob/master/ckanext/qa/resource_format_openness_scores.json#L31

**Comment by KrzysztofMadejski** [comment]
Z nowym QA dziala to tak:
```
[2017-03-15 10:52:09,446: INFO/PoolWorker-1] qa.update_package[atom-f9e6]: Sniffing file format of: /home/ckan/data/archiver/70/70dc3b00-2eda-4002-afab-1456abe38403/SU
[2017-03-15 10:52:09,468: INFO/PoolWorker-1] qa.update_package[atom-f9e6]: Magic detects file as: application/xml
[2017-03-15 10:52:09,469: INFO/PoolWorker-1] qa.update_package[atom-f9e6]: Top level tag detected as: feed
[2017-03-15 10:52:09,469: INFO/PoolWorker-1] qa.update_package[atom-f9e6]: XML variant detected: Atom Feed
[2017-03-15 10:52:09,470: INFO/PoolWorker-1] qa.update_package[atom-f9e6]: Score: 3 Reason: Content of file appeared to be format "Atom Feed" which receives openness score: 3.
[2017-03-15 10:52:09,470: INFO/PoolWorker-1] qa.update_package[atom-f9e6]: Openness scoring: 
{'openness_score_reason': 'Content of file appeared to be format "Atom Feed" which receives openness score: 3.', 'openness_score': 3, 'archival_timestamp': '2017-03-15T10:52:09.060633', 'format': 'Atom Feed'}

```

**Comment by k255** [comment]
Looks good!

**Comment by KrzysztofMadejski** [comment]
Zamknięte w #288
