### ISSUE TITLE
Przykłady API zepsute

### ISSUE THREAD

**Issue by ad-m** [DanePubliczneGovPl/ckanext-danepubliczne#276]
![prawa_jazdy _-_prawa_jazdy_w_2016_r _-_dane_publiczne_-_2016-09-30_11 50 40](https://cloud.githubusercontent.com/assets/3618479/18987955/a66c0de4-8704-11e6-898e-c90cffb5c291.png)

Przykładowo na https://danepubliczne.gov.pl/dataset/prawa-jazdy-wydane-w-2016-r/resource/b64fad89-c1d4-4dae-a971-4f6f17de0894 przykład SQL jest nieprawidłowy (https://danepubliczne.gov.pl/api/action/datastore_search_sql?sql=SELECT%20*%20from%20%22b64fad89-c1d4-4dae-a971-4f6f17de0894%22%20WHERE%20title%20LIKE%20%27jones%27 ).
![danepubliczne gov pl_api_action_datastore_search_sql_sql select 20_ 20from 20 22b64fad89-c1d4-4dae-a971-4f6f17de0894 22 20where 20title 20like 20 27jones 27_-_2016-09-30_11 55 34](https://cloud.githubusercontent.com/assets/3618479/18987985/d0ff6f9c-8704-11e6-928b-3acee45ed344.png)

**Comment by KrzysztofMadejski** [comment]
Poprawiłem, daj znać @ad-m czy jest ok

**Comment by ad-m** [comment]
Wygląda na to, że jest już OK.
