### ISSUE TITLE
Rozbieżności pomiędzy ```package_search``` i ```package_show```

### ISSUE THREAD

**Issue by ad-m** [DanePubliczneGovPl/ckanext-danepubliczne#277]
Szukam sobie przykładowo https://danepubliczne.gov.pl/api/3/action/package_search?sort=metadata_modified+desc&fq=%2Bdataset_type%3Adataset&rows=20&facet.field=%5B%22organization%22%2C+%22institution_type%22%2C+%22groups%22%2C+%22tags%22%2C+%22api%22%2C+%22res_format%22%2C+%22res_type%22%2C+%22update_frequency%22%2C+%22res_extras_openness_score%22%2C+%22has_any_reuse_conditions%22%5D&q=Rejestr+um%C3%B3w+i+zam%C3%B3wie%C5%84+finansowanych+&start=0 . Nigdy nie istnieje `results.resources.*.datastore_active`. Tymczasem dla https://danepubliczne.gov.pl/api/3/action/package_show?id=rejestr-zawartych-umow istnieje, co więcej ma wartość `true` w tym przypadku. Jest większość pól, więc wydawało się, że ten sam serializer co do dla szczegółowego. Dodatkowo utrudnione wyszukiwanie w `package_search` po samym ID utrudniło debugowanie.

Czy to jest gdzieś udokumentowane?

**Comment by KrzysztofMadejski** [comment]
Bo datastore_active przy `show` dla zasobów jest wyliczany dynamicznie, a podczas indeksowania, którego wyniki pokazywane są przy `search` przypisywany jest zbiorowi, a nie poszczególnym zasobom.
