### ISSUE TITLE
Nie każdy zbiór ma `update_frequency`

### ISSUE THREAD

**Issue by ad-m** [DanePubliczneGovPl/ckanext-danepubliczne#279]
```
In [24]: [x['id'] for x in ckan.action.package_search(rows=2000)['results'] if not "update_frequency" in x]
Out[24]: 
[u'482586e1-6c9d-4bd5-8daa-71b1d64d51fe',
 u'73980ac7-6bbc-4c81-8c61-06c3de69183c',
 u'f7ffb4c8-fb5a-403c-86ef-d398345c25b5',
 u'978eebb4-b6aa-44d0-aac5-c9c689c4c20b',
 u'd0da3283-e20e-4a5e-92c4-c31b141b7f8d',
 u'f940f0d5-d766-4c5f-8af4-6cf1afa37f53']
```

**Comment by ad-m** [comment]
Nie przyjrzałem się tym zbiorom. To są artykuły z bazy wiedzy. Zastanawiające i mało intuicyjne. Pozostawiam do rozważenia.

**Comment by KrzysztofMadejski** [comment]
Tak, tylko te `package`, które mają ustawiony `"type": "dataset"` mają ustawiony update_frequency, bo to są "zbiory danych" w systemie.

W czymś jeszcze mogę pomóc?

**Comment by ad-m** [comment]
Dziękuje, zrobiłem narzędzie, które chciałem. Watchdoguje CKAN. Niektóre
zbiory są błędnie nieaktualizowane. Mam też newsletter o zmianach.

Wysłano z urządzenia mobilnego.

3 paź 2016 10:02 AM "Krzysiek Madejski" <notifications@github.com>
napisał(a):

**Comment by KrzysztofMadejski** [comment]
CKAN Watchdog, lubię to. Jestem przekonany, że MC chętnie by zajrzało do wyników.

Czy ten issue mogę zamknąć?

**Comment by ad-m** [comment]
Tak.

MC już dostało wniosek na jego podstawie. Kod jest ogólnodostępny (mój
profil GitHub), ale póki co kalibruje, bo boję się spamu zbiorami
zmienianymi co dzień.

Tak, można zamknąć.

Wysłano z urządzenia mobilnego.

3 paź 2016 11:45 "Krzysiek Madejski" <notifications@github.com> napisał(a):

CKAN Watchdog, lubię to. Jestem przekonany, że MC chętnie by zajrzało do
wyników.

Czy ten issue mogę zamknąć?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/issues/279#issuecomment-251066428>,
or mute the thread
