### ISSUE TITLE
Nie znaleziono strony

### ISSUE THREAD

**Issue by SMagdalena** [DanePubliczneGovPl/ckanext-danepubliczne#309]
Aktualna strona: https://danepubliczne.gov.pl/dataset/9d3598a0-52d7-411b-9830-8c609a5bf19f/resource/012a5cb3-b9c6-48e9-9812-3fc780ab6a4c/download/GeobazaaPGW.zip

Z jakiej strony tu dotarłeś/aś: KZGW

Czego oczekiwałeś/aś: 
Brak możliwości pobrania danych. Dane nie są dostępne do pobrania pod wskazanym adresem.

**Comment by KrzysztofMadejski** [comment]
Już ten zasób jest dostępny, przepraszam za kłopot.
