### ISSUE TITLE
Uzupełnić informacje na temat wykonywania automatycznych

### ISSUE THREAD

**Issue by ad-m** [DanePubliczneGovPl/ckanext-danepubliczne#312]
W repozytorium znajdują się pliki ```.travis.yml``` odnoszący się do wykonywania testów automatycznych. Brak jest jednak informacji, gdzie dostępne są wyniki tych testów.

**Comment by KrzysztofMadejski** [comment]
To były pliki zawarte domyślnie w szkielecie pluginu. Z Travisa nie korzystaliśmy, więc pliki usunąłem.
