### ISSUE TITLE
Udokumentowanie budowania tłumaczeń

### ISSUE THREAD

**Issue by ad-m** [DanePubliczneGovPl/ckanext-danepubliczne#317]
Repozytorium zawiera w żaden sposób nieudokumentowane skrypty służace - jak przypuszczam - budowy plików tłumaczeń:

Standardowa metoda budowy tłumaczeń nie funkcjonuje ( http://docs.ckan.org/en/latest/extensions/translating-extensions.html#manually-create-translations ):

```
/vagrant $ python setup.py init_catalog -l pl
running init_catalog
creating catalog 'ckanext/danepubliczne/i18n/pl/LC_MESSAGES/ckanext-danepubliczne.po' based on 'ckanext/danepubliczne/i18n/ckanext-danepubliczne.pot'
error: [Errno 2] No such file or directory: 'ckanext/danepubliczne/i18n/ckanext-danepubliczne.pot'
$ python setup.py update_catalog --locale pl
running update_catalog
error: [Errno 2] No such file or directory: 'ckanext/danepubliczne/i18n/ckanext-danepubliczne.pot'
```

Nieudokumentowane skrypty nie wspierają standardowego wywołania:
```
/vagrant/ckanext/danepubliczne/i18n$ ./aggregate_and_compile.sh 
Processing lang en
  Translation danepubliczne[en] doesn't exist. Missing //ckanext-danepubliczne/ckanext/danepubliczne/i18n/en/LC_MESSAGES/ckanext-danepubliczne.po
  Translation qa[en] doesn't exist. Missing //ckanext-qa/ckanext/qa/i18n/en/LC_MESSAGES/ckanext-qa.po
  Translation archiver[en] doesn't exist. Missing //ckanext-archiver/ckanext/archiver/i18n/en/LC_MESSAGES/ckanext-archiver.po
  Translation report[en] doesn't exist. Missing //ckanext-report/ckanext/report/i18n/en/LC_MESSAGES/ckanext-report.po
  Aggregating translations for en from files:  ckan[override]. First defined translation takes precedence
    msgcat --use-first  /vagrant/ckanext/danepubliczne/i18n/en/LC_MESSAGES/ckan_override.po -o /vagrant/ckanext/danepubliczne/i18n/en/LC_MESSAGES/ckan.po
  Compiling translations for en
    msgfmt /vagrant/ckanext/danepubliczne/i18n/en/LC_MESSAGES/ckan.po -o /vagrant/ckanext/danepubliczne/i18n/en/LC_MESSAGES/ckan.mo
/vagrant/ckanext/danepubliczne/i18n$ ./unique_pot.sh 
msgcat: error while opening "//ckan/ckan/i18n/ckan.pot" for reading: No such file or directory
msgcat: error while opening "/vagrant/ckanext/danepubliczne/i18n/ckanext-danepubliczne.pot" for reading: No such file or directory
rm: cannot remove '/vagrant/ckanext/danepubliczne/i18n/ckanext-danepubliczne-reused.pot': No such file or directory

```

**Comment by KrzysztofMadejski** [comment]
> Standardowa metoda budowy tłumaczeń nie funkcjonuje
Ponieważ plik `.pot` nie jest zakomitowany.

Tworzenie tłumaczeń udokumentowane jest tutaj: https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/wiki/Modifying-translations

Skrypt `aggregate_and_compile.sh` jest po to, aby:
- Móc trzymać pełne polskie tłumaczenia dla CKAN'a niezależnie od oryginalnego repo -> https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/blob/develop/ckanext/danepubliczne/i18n/pl/LC_MESSAGES/ckan_override.po
- Móc nadpisać te oryginalne tłumaczenia CKANowe, używanymi w danych publicznych (np. Dostawca zamiast Organizacja), a także uzupełnić je tłumaczeniami wyjątkowymi dla ckanext-danepubliczne https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/blob/develop/ckanext/danepubliczne/i18n/pl/LC_MESSAGES/ckanext-danepubliczne.po

Skrypt `[unique_pot.sh](https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/blob/develop/ckanext/danepubliczne/i18n/unique_pot.sh)` generuje unikalny plik `.pot` dzięki czemu mamy w nim wyłącznie translacje właściwe dla ckanext-danepubliczne (usuwa on teksty reużyte z oryginalnego CKAN)

**Comment by ad-m** [comment]
@KrzysztofMadejski , dziękuje za wyjaśnienia! Przegapiłem podstronę w Wiki. Przepraszam.
