### ISSUE TITLE
Flash message

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#32]
Do ostylowania. Maksymalnie mogą się wyświetlać dwa takie flashe.

Typy:
- ckan.lib.helpers.flash_notice(message, allow_html=False)
- ckan.lib.helpers.flash_error(message, allow_html=False)
- ckan.lib.helpers.flash_success(message, allow_html=False)¶

Będziemy używać tego mechnizmu do wyświetlania informacji o planowanej przerwie technicznej. (oprócz standardowych komunikatów zwracanych przez CKAN).

![dane-publiczne-flash](https://cloud.githubusercontent.com/assets/849975/6460602/d3a2788a-c198-11e4-81d9-a2353e31fa83.png)

**Comment by KrzysztofMadejski** [comment]
Teraz to tak wygląda, całkiem nieźle już :)

![ckan-flash-existing](https://cloud.githubusercontent.com/assets/849975/6462398/02c21084-c1a9-11e4-9606-0afda4b1c2e8.png)

**Comment by ArekSoldon** [comment]
No spoko jest... jeżeli tylko font się zgadza to zostawmy - im mneij zmineniania dla Mario tym lepiej :P
