### ISSUE TITLE
Nie znaleziono strony

### ISSUE THREAD

**Issue by Sayene** [DanePubliczneGovPl/ckanext-danepubliczne#322]
Aktualna strona: https://danepubliczne.gov.pl/dataset/c4b278de-d141-47dd-9971-35ca109185b9/resource/d262d817-26e3-4f57-a781-90790aafa0de/download/TPA-gaz-za-III-kw.-2017-r.xlsx

Z jakiej strony tu dotarłeś/aś: 
https://danepubliczne.gov.pl/dataset/liczba-zmian-sprzedawcy-gazu-ziemnego-przez-odbiorcow-koncowych/resource/d262d817-26e3-4f57-a781-90790aafa0de
Czego oczekiwałeś/aś:
zasobu - pliku do pobrania

**Comment by KrzysztofMadejski** [comment]
Problem został rozwiązany, proszę spróbować ponownie. Przepraszam za niedogodności.
