### ISSUE TITLE
Responsive look [3]

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#33]
Do przegadania live 17 marca, jak będą zakodowane już inne widoki

**Comment by KrzysztofMadejski** [comment]
Uwzględnić uwagę https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/issues/15#issuecomment-77373687

**Comment by ArekSoldon** [comment]
wszystko opisane na screenach, nie ma tego dużo :) 

![screen-shot-2015-03-24-at-11_21_29](https://cloud.githubusercontent.com/assets/3994690/6799828/4a7c5062-d219-11e4-991f-0bb2d87bec98.png)
![screen-shot-2015-03-24-at-11_21_26](https://cloud.githubusercontent.com/assets/3994690/6799831/4aa993f6-d219-11e4-96ae-c21728f48c3c.png)
![screen-shot-2015-03-24-at-11_22_32](https://cloud.githubusercontent.com/assets/3994690/6799830/4aa35644-d219-11e4-9e48-46b71df54ed1.png)
![screen-shot-2015-03-24-at-11_21_31](https://cloud.githubusercontent.com/assets/3994690/6799829/4aa360a8-d219-11e4-84c9-7a68df40a757.png)
![screen-shot-2015-03-24-at-11_22_00](https://cloud.githubusercontent.com/assets/3994690/6799832/4ab27c0a-d219-11e4-8cdb-97e75a7f91ad.png)

**Comment by KrzysztofMadejski** [comment]
menu mi wyjezdza ![screenshot_2015-03-27-16-26-25](https://cloud.githubusercontent.com/assets/849975/6872016/d61c277a-d4a6-11e4-9a3a-962e6fc3ff18.png)
