### ISSUE TITLE
Pojedynczy zasób [2]

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#35]
@ArekSoldon wydzielam z #24 

Zasób:

Jeżeli wgrywamy csv-kę to jest podgląd danych oraz przycisk `Data API`
![ckan-resource-data](https://cloud.githubusercontent.com/assets/849975/6414880/34296692-be9b-11e4-97ea-4b124fb1255e.PNG)

Każdy zasób ma 'gwiazdki otwartości':
![ckan-resource-rating](https://cloud.githubusercontent.com/assets/849975/6414889/419e8352-be9b-11e4-9384-5761d7c17adf.PNG)

Zalogowanym użytkownikom posiadającym uprawnienia do edycji powinien się pojawiać przycisk pozwalający na edycję (zarówno datasetu, jak i zasobu). Patrz `Manage`
![ckan-resource-edit](https://cloud.githubusercontent.com/assets/849975/6414926/8dfdaf2a-be9b-11e4-90bb-2f5dcb90b2b5.PNG)
:

**Comment by ArekSoldon** [comment]
![csv](https://cloud.githubusercontent.com/assets/3994690/6521316/9f17e95c-c3d6-11e4-958c-fd90c99ee2f7.jpg)

**Comment by KrzysztofMadejski** [comment]
@dominiku Prośba o komenty. 

Sekcji "Udostępnij na FB, itp." nie będzie

**Comment by shutdownrunner** [comment]
Może lepiej mówić o stopniu otwartości zamiast gwiazdek otwartości? Gwiazdami otwartości będą podmioty, które jako pierwsze osiągną 5 stopień otwartości. 

Jeśli zasób ma 3/5, powinny być 3 gwiazdki zapełnione i 2 puste. Dzięki temu łatwiej skojarzyć, że maksymalny wynik to 5.

**Comment by KrzysztofMadejski** [comment]
"Gwiazdy otwartości" :)

Tak, też pomyślałem o tym, żeby to był "Stopień otwartości". Uwaga o pustych gwiazdkach bardzo słuszna.

Odnośnie układu: myślę, o tym żeby przenieść Stopień Otwartości nad url, zaraz pod tytułem. 

Podobnie warunki i metadane, chyba powinny polecieć wyżej nad wizualizację, pod opis.

**Comment by ArekSoldon** [comment]
![csv](https://cloud.githubusercontent.com/assets/3994690/6684047/8045d4a2-cc8d-11e4-8227-62fefbdab7f7.jpg)

**Comment by KrzysztofMadejski** [comment]
@dominiku @jadebs przypominam się z tym.

@Cain-Ish jak będziesz wolny to możesz zacząć wdrażać, bo pewnie rewolucjnych zmian nie będzie.

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish: URL do konkretnego zasobu powinien mieć przypisaną klasę `piwik_download` ref #5

**Comment by dominiku** [comment]
Tak,  dzięki za przypomnienie (pamiętaliśmy) ale @jadebs zaraz Wam podrzuci
komentarze.

**Comment by jadebs** [comment]
![fireshot pro screen capture 906 - -](https://cloud.githubusercontent.com/assets/11333543/6686573/248c5850-cca3-11e4-8841-e426bebc0753.png)

**Comment by KrzysztofMadejski** [comment]
@jadebs Dzięki!

**Comment by KrzysztofMadejski** [comment]
Dodałem openess score u góry.

- [ ] wystylować openess score
- [ ] przycisk `Data API` na niebiesko
- [ ] Data Explorer (lub inna wizualizacja) powinnien być jako Tab (navbar) a nie przycisk, bo wiele się ich może pojawić. Może zrobić wyszarzony panel który będzie zawierał taby i cały content? Przegadajmy to razem.
- [ ] na dole mi się wyświetla jakiś pusty szary box, do wywalenia??

  ```
<div class="dataset-result span9">
                  <article class="module">
                      <header class="module-content page-header">
                        <ul class="nav nav-tabs">
                        </ul>
                      </header>
                    <div class="module-content">
                    </div>
                  </article>                
              </div>
  ```

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish  tu też się trzeba zmergować z develop. Poprawki do zrobienia wyżej wypisałem
