### ISSUE TITLE
Logo w dwóch nowych wersjach

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#42]
@ArekSoldon przygotuj proszę dwa loga, które będą mieć widocznie wklejone oznaczenia (np. na czzerwonym tle):
- wersja szkoleniowa
- wersja deweloperska

**Comment by ArekSoldon** [comment]
![dev](https://cloud.githubusercontent.com/assets/3994690/6553416/c9d88058-c650-11e4-99e3-833a577e1bd5.png)
![szkoleniowa](https://cloud.githubusercontent.com/assets/3994690/6553417/ca13bf24-c650-11e4-80a3-31435cb72a4f.png)

**Comment by ArekSoldon** [comment]
tylko do podmiany - rozmair identycnzy z tym z deva :)

**Comment by KrzysztofMadejski** [comment]
dzięki!

**Comment by KrzysztofMadejski** [comment]
Gdzie ściana wschodnia?! :warning:

**Comment by ArekSoldon** [comment]
na wschodzie :P 
![szkoleniowa](https://cloud.githubusercontent.com/assets/3994690/6684315/7238a684-cc90-11e4-819f-2440553ac497.png)
![dev](https://cloud.githubusercontent.com/assets/3994690/6684316/723b3318-cc90-11e4-8802-9420768fe215.png)

**Comment by ArekSoldon** [comment]
![bez](https://cloud.githubusercontent.com/assets/3994690/6684344/a9e34670-cc90-11e4-9561-414f753b29e1.png)
