### ISSUE TITLE
Admin tabs

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#48]
Jakiś prościutki layout pod zakładki admina potrzebuję, bo teraz się zlewają. Zakładki trzeba jakoś odróżnić od ich treści. Może je wrzucić w niebieski pasek jakiś? Bo góra i dół muszą być białe. A lewą stronę z opisem wyszarzyć jak na obecnym loginie: http://dp-dev.epf.p5.tiktalik.io/user/login

![ckan-admin](https://cloud.githubusercontent.com/assets/849975/6644430/04d09a86-c9b4-11e4-8616-8fc1e2178dba.png)

**Comment by ArekSoldon** [comment]
dałbym zamiast tego szarego gradient od szarego do białego, i taby wyrównać do dołu, fonty jak wszędzie, ikonki zostawić jak są obecnie i będzie gitarra... 

![tabs](https://cloud.githubusercontent.com/assets/3994690/6686076/9560157a-cc9f-11e4-853a-8799563eecf7.jpg)

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish 
`admin/base.html` tak trzeba wystylować.

Jeżeli to będzie wymagało ruszenia `page.html` to wtedy nie ma co page duplikować tylko będę musiał helper dorobić:

```
class="{% if h.dp_is_admin_controller() -%}klasa_gradientu{% endif %}
```
