### ISSUE TITLE
Lista artykułów na głównej

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#85]
- Artykuły w sekcji "Artykuły" na głównej dać w liście <ul>
- linki "czytaj więcej" uzupełnić o ukrytą treść, która dojaśni ich znaczenie niewidomym 

Podpowiedzi:
polecana technika dostępnego ukrywania: .ukryte { position: absolute; clip: rect(1px 1px 1px 1px); clip: rect(1px,1px,1px,1px); padding: 0; border: 0; height: 1px; width: 1px; overflow: hidden; }

**Comment by Cain-Ish** [comment]
Artykuły w sekcji "Artykuły" na głównej dać w liście
