### ISSUE TITLE
Widoczność fokusu klawiatury

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#87]
Wzmocnić ramkę fokusu - obecnie na kafelkach na głównej, na polach formularzy czy w stopce jest praktycznie niewidoczny. 

Podpowiedź:
Mam nadzieję, że nie zadam ciosu poniżej pasa projektantowi wizuala, ale np. ramka soczysta żółć, 2 px byłaby widoczna chyba wszędzie. To pokombinowania.

**Comment by Cain-Ish** [comment]
Ustawiono wstępnie kolor yellow (#FFFF00) solid 2px oraz usunięto outline:0 z reset.css.

Kolor do przemyślenia @KrzysztofMadejski

**Comment by KrzysztofMadejski** [comment]
Kolor ok. Jak już ktoś używa to niech widzi.
