### ISSUE TITLE
Graficzne elementy dekoracyjne

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#88]
Muszą mieć pusty opis alternatywny: <alt="">
1. w ikonach kategorii np. na http://dp-dev.epf.p5.tiktalik.io/group/administracja_publiczna dać puste alty,
2. avatary np. w historii http://dp-dev.epf.p5.tiktalik.io/dataset/activity/program_operacyjny_innowacyjna_gospodarka__2007_2013___analizy__raporty_i_podsumowania - nie ma wogóle alt - dodać pusty alt=””
3. w listingu Organizations http://dp-dev.epf.p5.tiktalik.io/organization zbędna treść w altach kafelków - dać puste alty
4. zbędna treść alt na ikonie/logo organizacji w pojedynczej organizacji np. http://dp-dev.epf.p5.tiktalik.io/organization/glowny_inspektorat_ochrony_srodowiska
5. gwiazdki otwartości na np. http://dp-dev.epf.p5.tiktalik.io/dataset/dlug_publiczny/resource/53fda09fbdd0789a545ddbf6 - dać im alt puste (nie mają wcale altów) i w formie ukrytej treści (clip) informację o poziomie otwartości np. “3 na 5”, "4 na 5" etc.

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish te alty już do zamknięcia?
