### ISSUE TITLE
Kontarst treści do tła

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#89]
1. linki w headerze dataseta z nazwą właściciela i do źródła - 3,6:1 a minimum to 4,5:1
2. to samo w historii zmian np. http://dp-dev.epf.p5.tiktalik.io/dataset/activity/program_operacyjny_innowacyjna_gospodarka__2007_2013___analizy__raporty_i_podsumowania tyle że tu dochodzą jeszcze jasnoszare informacje kiedy wprowadzono zmiany (to samo w activity stream w pojedynczych organizacjach)
3. zakładki w pojedynczej organizacji np. http://dp-dev.epf.p5.tiktalik.io/organization/glowny_inspektorat_ochrony_srodowiska 
4. kontarst linków tekstowych do tła http://dp-dev.epf.p5.tiktalik.io/about

Podpowiedź:
Minimum to 4,5:1 ale optimum 7:1.

**Comment by Cain-Ish** [comment]
@ArekSoldon możesz na to rzucić okiem i zapodać hex nowych kolorów?

**Comment by ArekSoldon** [comment]
1. #157abe  - wynik będzie 4,61
2. linki jak w 1 szare #160 3. 757575
3. nazwę zróbmy czarną
4. jak 1.
