### ISSUE TITLE
Filtrowanie datasetów

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#92]
1. wybrany filtr oznaczony tylko wizualnie - dodać info o użytych filtrach w tytule strony i gdzieś na poziomie h2 na początku listy wyników - zamiast “17 dataset found” to “17 wyników dla <info o użytych filtrach>”
2. Problem z odkliknięciem wybranego filtra - pojawia się tylko wizualny X sugerujący zamknięcie
3. dodać ukrytą treść pod h2 Filtry - wyjaśniającą niewidomym jak działa filtr, i że np. liczby w nawiasie oznaczają ile jest spełniających dany filtr elementów etc.

**Comment by Cain-Ish** [comment]
Do rozkminienia numer 3.
