### ISSUE TITLE
Listing datasetów (uwagi do szablonu)

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#93]
1. niedostępne i nieużyteczne linki tytułujące datasety, ze względu na ich ucinanie np. mój ulubiony “Wytyczne w zakresie sposoby postępowania w razie wykrycia nieprawidłowości w…”
2. podobny problem z ucinanymi zajawkami pod tytułami, chociaż tutaj już nie jest to aż tak rażące,
3. zbędna funkcja linków na typach plików w danym datasecie - i tak każdy prowadzi do strony datasetu i potem ręcznie trzeba wybrać interesujący format
4. uzytecznościowo - te typy plików w listingu odczytałem, jako zapowiedź, że wszystkie dane w datasecie mam w jednym bądź kilku formatach do wyboru. Tymczasem to raczej informacja jakiego typu pliki są w środku, tyle że część danych w jednym a inne w drugim formacie.

**Comment by Cain-Ish** [comment]
3. zbędna funkcja linków na typach plików w danym datasecie - i tak każdy prowadzi do strony datasetu i potem ręcznie trzeba wybrać interesujący format
