### ISSUE TITLE
Pojedynczy dataset (uwagi do szablonu)

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#94]
1. zbędna pusta lista <ul> w headerze
2. niezrozumiałe działanie linków w “Słowach kluczowych” - jest to tak naprawde filtrowanie przerzucające do innych listingów - można podobnie jak w filtorwaniu dodać akapit niewidoczny ale dla czytników dostępny mówiący jak to działa,
3. niezrozumiałe linki do pobrania
- same nazwy plików ścinane jeszcze bardziej niż listingu datasetów,
- powtarzające się linki “preview” “go to resource” etc. prowadzące do różnych treści - dodać ukrytą treść rozwijającą ich znaczenie,
- tytuł pliku i “preview” i “more information” prowadzą do tych samych stron - why?

**Comment by Cain-Ish** [comment]
niezrozumiałe działanie linków w “Słowach kluczowych” - jest to tak naprawde filtrowanie przerzucające do innych listingów - można podobnie jak w filtorwaniu dodać akapit niewidoczny ale dla czytników dostępny mówiący jak to działa,
