### ISSUE TITLE
O serwisie (uwagi do szablonu)

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#97]
1. brak nagłówka h1
2. dodać h2 z pytaniami w liście <ol> - obecnie to tylko wizualnie lista
3. kontrast linków wskazany wcześniej,
4. w ostatnim akapicie mowa o możliwości zgłaszania uwag w pojedynczym datasecie, ale tej funckji nie ma (przynjamniej nie widzę jej będąc niezalogowanym)

**Comment by KrzysztofMadejski** [comment]
@shutdownrunner przekazuję sugestie odnośnie formatowania treści na stronie "O serwisie"

```markdown
# O serwisie (h1)

## Pytania i odpowiedzi (h2)

<dl>
  <dt>Pytanie 1</dt>
  <dd>Odpowiedz 1</dd>
  <dt>Pytanie 2</dt>
  <dd>Odpowiedz 2</dd>
</dl>
```
