### ISSUE TITLE
Zakładanie konta (uwagi do szablonu)

### ISSUE THREAD

**Issue by jadebs** [DanePubliczneGovPl/ckanext-danepubliczne#99]
1. brak informacji o wymaganiach dotyczących hasła - pojawia się dopiero po nieudanej próbie wpisania zbyt krótkiego hasła
2. brak weryfikacji zapisu - można obecnie na dowolny mail zakładać konto 
3. kontrast informacji o błędzie zbyt mały (róż do różu)

**Comment by Cain-Ish** [comment]
Fix 1.
